loadBalancerClass: homelab-metallb

prometheus:
  # the service account used by prometheus
  # required when " .Values.prometheus.rbacPrometheus == true " and " .Values.prometheus.podMonitor.enabled=true or prometheus.serviceMonitor.enabled=true "
  serviceAccount: "prometheus-operator-kube-p-prometheus"
  # the namespace where prometheus is deployed
  # required when " .Values.prometheus.rbacPrometheus == true " and " .Values.prometheus.podMonitor.enabled=true or prometheus.serviceMonitor.enabled=true "
  namespace: "operators"
  # Prometheus Operator PodMonitors
  podMonitor:
    # enable support for Prometheus Operator
    enabled: true
    # Job label for scrape target
    jobLabel: "app.kubernetes.io/metallb"

  # Prometheus Operator ServiceMonitors. To be used as an alternative
  # to podMonitor, supports secure metrics.
  serviceMonitor:
    # enable support for Prometheus Operator
    enabled: true

    # Job label for scrape target
    jobLabel: "app.kubernetes.io/metallb"

# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  enabled: true
  # -- Controller log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
  logLevel: info
  tolerations:
    - key: "nas"
      operator: "Equal"
      value: "true"
      effect: NoSchedule

# speaker contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  enabled: true
  # command: /speaker
  # -- Speaker log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
  logLevel: info
  tolerations:
    - key: "nas"
      operator: "Equal"
      value: "true"
      effect: NoSchedule

crds:
  enabled: true
  validationFailurePolicy: Fail
