apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  labels:
    app: tdarr
    use: config
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-logs
  labels:
    app: tdarr
    use: logs
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-srv
  labels:
    app: tdarr
    use: server
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-transode-cache
  labels:
    app: tdarr
    use: transcode
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-ephemeral-r1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
