kind: Service
apiVersion: v1
metadata:
  name: tdarr
  labels:
    app.kubernetes.io/name: tdarr
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    external-dns.alpha.kubernetes.io/hostname: tdarr.homelab.local
    # Get Homepage configuration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Video library transcoding
    gethomepage.dev/group: Home
    gethomepage.dev/icon: tdarr.png
    gethomepage.dev/name: Tdarr
    gethomepage.dev/href: http://tdarr.<homelab-domain>
    gethomepage.dev/widget.type: "tdarr"
    gethomepage.dev/widget.url: "http://tdarr"
spec:
  selector:
    app.kubernetes.io/name: tdarr
  type: LoadBalancer
  loadBalancerClass: homelab-metallb
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8265
    - protocol: TCP
      name: server
      port: 8266
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  annotations:
    app.kubernetes.io/name: tdarr
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tdarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tdarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/nas
                    operator: In
                    values:
                      - "nas"
      tolerations:
        - key: "nas"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      automountServiceAccountToken: false
      containers:
      - name: tdarr
        image: haveagitgat/tdarr:2.36.01
        imagePullPolicy: Always
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: serverIP
            value: "0.0.0.0"
          - name: serverPort
            value: "8266"
          - name: webUIPort
            value: "8265"
          - name: internalNode
            value: "true"
          - name: nodeID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        ports:
          - containerPort: 8265
            name: ui
          - containerPort: 8266
            name: server
        volumeMounts:
          - mountPath: /app/configs
            name: config
          - mountPath: /app/server
            name: server
          - mountPath: /app/logs
            name: logs
          - mountPath: /temp
            name: transcode-cache
          - mountPath: /video
            name: video
          # VIDEO
          - mountPath: /dev/dri
            name: dri
      volumes:
        - name: logs
          hostPath:
            type: Directory
            path: <NFS_STOR_0_PATH>/system/tdarr/logs
        - name: config
          hostPath:
            type: Directory
            path: <NFS_STOR_0_PATH>/system/tdarr/config
        - name: server
          hostPath:
            type: Directory
            path: <NFS_STOR_0_PATH>/system/tdarr/server
        - name: transcode-cache
          hostPath:
            type: Directory
            path: <NFS_STOR_0_PATH>/system/tdarr/cache
        - name: video
          hostPath:
            type: Directory
            path: <NFS_STOR_0_PATH>/multimedia/video
        # VIDEO
        - name: dri
          hostPath:
            path: /dev/dri
