apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  labels:
    app: navidrome
    use: data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  labels:
    app: navidrome
    use: media
spec:
  storageClassName: rook-media-r1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
