apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  docker.yaml: ''
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Global:
        - ArgoCD:
            href: https://argocd.<homelab-domain>
            description: Kubernetes CI/CD
            icon: argo-cd.png
        - Traefik:
            href: https://dash-traefik.<homelab-domain>
            description: Traefik proxy
            icon: traefik.png
            widget:
              type: traefik
              url: https://dash-traefik.<homelab-domain>
        - Keycloak:
            href: https://keycloak.<homelab-domain>
            description: OIDC provider
            icon: keycloak.png
        - Minio:
            href: https://minio-admin.<homelab-domain>
            description: S3-compatible object storage
            icon: minio.png
        - Grafana:
            href: https://grafana.<homelab-domain>
            description: Dashboards and monitoring
            icon: grafana.png
        - Technitium:
            href: http://dnsa.<homelab-domain>
            description: DNS Server
            icon: technitium.png
        - Rook main:
            href: https://rook-main.<homelab-domain>
            description: Rook storage server
            icon: rook.png
    - Dev Env:
        - Gitea:
            href: https://git.<homelab-domain>
            description: Git repository
            icon: gitea.png
        - Sonarqube:
            href: https://sonarqube.<homelab-domain>
            description: Code quality analysis
            icon: sonarqube.png
        - Harbor:
            href: https://harbor.<homelab-domain>
            description: Container registry
            icon: harbor.png
        - PgAdmin:
            href: https://pgadmin.<homelab-domain>
            description: PostgreSQL management
            icon: pgadmin.png
        - OpenProject:
            href: https://openproject.<homelab-domain>
            description: Project management
            icon: openproject.png
        - IT tools:
            href: https://tools.<homelab-domain>
            description: Various IT and Developer tools
            icon: it-tools.png
    - Home:
        - Audiobookshelf:
            href: https://audiolib.<homelab-domain>
            description: Audio Books
            icon: audiobookshelf.png
            widget:
              type: audiobookshelf
              url: http://audiobookshelf
              key: <path:kv/data/homepage#audiobookshelf-key>
        - Immich:
            href: https://gallery.<homelab-domain>
            description: Photo gallery
            icon: immich.png
            widget:
              type: immich
              url: http://immich-server:2283
              key: <path:kv/data/homepage#immich-key>
              version: 2
        - Nextcloud:
            href: https://nextcloud.<homelab-domain>
            description: File manager & File Sharing
            icon: nextcloud.png
        - Homebox:
            href: https://homebox.<homelab-domain>
            description: Inventory management
            icon: homebox.png
        - Homeassistant:
            href: https://ha.<homelab-domain>
            description: Home automations
            icon: home-assistant.png
            widget:
              type: homeassistant
              url: "https://ha.<homelab-domain>"
              key: <path:kv/data/homepage#homeassistant-key>
              custom:
                - state: sensor.owlery_realfeel_temperature_max_day_1
                  label: Temperature
                - state: sensor.owlery_condition_day_1
                  label: Weather
        - Calibre:
            href: https://books.<homelab-domain>
            description: Electronic books
            icon: calibre-web.png
            widget:
              type: calibreweb
              url: http://calibre:8083
              username: <path:kv/data/homepage#calibre-username>
              password: <path:kv/data/homepage#calibre-password>
        - Mealie:
            href: https://mealie.<homelab-domain>
            description: Recipes
            icon: mealie.png
            widget:
              type: mealie
              url: http://mealie:9000
              key: <path:kv/data/homepage#mealie-key>
              version: 2
        - Barassistant:
            href: https://bar.<homelab-domain>
            description: Bar & Coctails
            icon: bar-assistant.png
    - Multimedia:
        - Jellyfin:
            href: https://video.<homelab-domain>
            description: Video streaming
            icon: jellyfin.png
            widget:
              type: jellyfin
              url: https://jellyfin:443
              key: <path:kv/data/homepage#jellyfin-key>
              enableBlocks: "true"
              enableNowPlaying: "false"
              enableUser: "true"
              showEpisodeNumber: "true"
              expandOneStreamToTwoRows: "false"
        - Navidrome:
            href: https://music.<homelab-domain>
            description: Music streaming
            icon: navidrome.png
        - Jellyseerr:
            href: https://jellyseerr.<homelab-domain>
            description: Media requests
            icon: jellyseerr.png
            widget:
              type: jellyseerr
              url: http://jellyseerr:5055
              key: <path:kv/data/homepage#jellyseer-key>
        - Radarr:
            href: https://radarr.<homelab-domain>
            description: Movies downloader
            icon: radarr.png
            widget:
              type: radarr
              url: http://radarr:7878
              key: <path:kv/data/homepage#radarr-key>
        - Sonarr:
            href: https://sonarr.<homelab-domain>
            description: TV Shows downloader
            icon: sonarr.png
            widget:
              type: sonarr
              url: http://sonarr:8989
              key: <path:kv/data/homepage#sonarr-key>
              enableQueue: "true"
        - Lidarr:
            href: https://lidarr.<homelab-domain>
            description: Music downloader
            icon: lidarr.png
            widget:
              type: lidarr
              url: http://lidarr
              key: <path:kv/data/homepage#lidarr-key>
        - Torrent:
            href: https://torrent.<homelab-domain>
            description: Torrent client
            icon: qbittorrent.png
            widget:
              type: qbittorrent
              url: http://qbittorrent
              username: <path:kv/data/homepage#qbittorrent-login>
              password: <path:kv/data/homepage#qbittorrent-pass>
        - Jackett:
            href: https://jackett.<homelab-domain>
            description: Torrent management
            icon: jackett.png
            widget:
              type: jackett
              url: http://jackett:9117
              password: <path:kv/data/homepage#jackett-pass>
  settings.yaml: |
    layout:
      Home:
        columns: 4
        style: row
        useEqualHeights: true
      Multimedia:
        columns: 4
        style: row
        useEqualHeights: true
      Global:
        columns: 4
        initiallyCollapsed: true
        style: row
        useEqualHeights: true
      Dev Env:
        columns: 4
        initiallyCollapsed: true
        style: row
        useEqualHeights: true
    title: Mornery Homelab
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
