apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-blocks
spec:
  bucketName: mimir-blocks
  storageClassName: rook-ceph-system-ssd-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-alertmanager
spec:
  bucketName: mimir-alertmanager
  storageClassName: rook-ceph-system-ssd-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-ruler
spec:
  bucketName: mimir-ruler
  storageClassName: rook-ceph-system-ssd-bucket
