global:
  extraEnv:
    - name: BLOCKS_AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mimir-blocks
          key: AWS_SECRET_ACCESS_KEY
    - name: BLOCKS_AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mimir-blocks
          key: AWS_ACCESS_KEY_ID
    - name: RULER_AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mimir-ruler
          key: AWS_SECRET_ACCESS_KEY
    - name: RULER_AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mimir-ruler
          key: AWS_ACCESS_KEY_ID
    - name: ALERTMANAGER_AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mimir-alertmanager
          key: AWS_SECRET_ACCESS_KEY
    - name: ALERTMANAGER_AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mimir-alertmanager
          key: AWS_ACCESS_KEY_ID
  extraArgs:
    - -config.expand-env=true

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          insecure: true
          endpoint: rook-ceph-rgw-system-ssd.rook-ceph.svc:80
    blocks_storage:
      s3:
        bucket_name: mimir-blocks
        secret_access_key: ${BLOCKS_AWS_SECRET_ACCESS_KEY}
        access_key_id: ${BLOCKS_AWS_ACCESS_KEY_ID}
    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager
        secret_access_key: ${ALERTMANAGER_AWS_SECRET_ACCESS_KEY}
        access_key_id: ${ALERTMANAGER_AWS_ACCESS_KEY_ID}
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
        secret_access_key: ${RULER_AWS_SECRET_ACCESS_KEY}
        access_key_id: ${RULER_AWS_ACCESS_KEY_ID}
runtimeConfig:
  ingester_limits: # limits that each ingester replica enforces
    max_ingestion_rate: 2000000
    max_series: 1500000
    max_tenants: 1000
    max_inflight_push_requests: 30000
  distributor_limits: # limits that each distributor replica enforces
    max_ingestion_rate: 2000000
    max_inflight_push_requests: 30000
    max_inflight_push_requests_bytes: 50000000

alertmanager:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false
  zoneAwareReplication:
    enabled: false

ingester:
  replicas: 2
  extraArgs:
    usage-stats.enabled: false
  zoneAwareReplication:
    enabled: false

overrides_exporter:
  extraArgs:
    usage-stats.enabled: false

store_gateway:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false
  zoneAwareReplication:
    enabled: false

distributor:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false
    distributor.ingestion-rate-limit: "50000"
    distributor.ingestion-burst-size: "1000000"

querier:
  replicas: 2
  extraArgs:
    usage-stats.enabled: false

query_frontend:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

query_scheduler:
  replicas: 2
  extraArgs:
    usage-stats.enabled: false

ruler:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

ruler_querier:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

ruler_query_frontend:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

ruler_query_scheduler:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

compactor:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false
    compactor.block-upload-enabled: true
    compactor.block-ranges: 14400h
    compactor.block-upload-max-block-size-bytes: "15000000000"

index-cache:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

metadata-cache:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

results-cache:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

chunks-cache:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

admin-cache:
  replicas: 1
  extraArgs:
    usage-stats.enabled: false

nginx:
  # Deprecated, use gateway
  enabled: false

gateway:
  enabledNonEnterprise: true
  replicas: 1
  ingress:
    enabled: false
  nginx:
    config:
      clientMaxBodySize: 15G
      enableIPv6: false

# Use standalone minio installation
minio:
  enabled: false
