apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashicorp-vault
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: vault.homelab.local
spec:
  ingressClassName: nginx-internal
  rules:
  - host: vault.<homelab-domain>
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hashicorp-vault
              port:
                number: 8200
  tls:
    - hosts:
      - vault.<homelab-domain>
      secretName: "vault.<homelab-domain>-cert"

