apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hashicorp-vault-data-nfs
  labels:
    app: hashicorp
    use: data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: hashicorp-vault-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashicorp-vault-data
  labels:
    app: hashicorp
    use: data
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <NFS_STOR_0_PATH>/system/vault
    server: <NFS_STOR_0_SERVER>
