apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
spec:
  selector:
    app.kubernetes.io/name: jellyseerr
  ports:
    - port: 5055
      targetPort: jellyseerr
      name: jellyseerr
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/name: jellyseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyseerr
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:2.5.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5055
              protocol: TCP
              name: jellyseerr
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr-config
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "Europe/Kyiv"
            - name: PORT
              value: "5055"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-jellyseerr-app
                  key: host
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-jellyseerr-app
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-jellyseerr-app
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-jellyseerr-app
                  key: dbname
            - name: DB_LOG_QUERIES
              value: "false"
          securityContext:
            runAsUser: 65534
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 750m
              memory: 1Gi
              ephemeral-storage: 256Mi
      volumes:
        - name: jellyseerr-config
          persistentVolumeClaim:
            claimName: jellyseerr-data
