apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-hl-ssl
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: argocd-server-tls
  renewBefore: 240h
  duration: 2160h
  commonName: argocd.<homelab-domain>
  dnsNames:
    - argocd.<homelab-domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
