auth:
  username: user
  existingSecret: airflow-auth

Executor: KubernetesExecutor

defaultInitContainers:
  loadDAGsPlugins:
    extraEnvVars:
      - name: GIT_SSL_NO_VERIFY
        value: "true"
      - name: GIT_SYNC_PULL
        value: "always"
      - name: GIT_SYNC_REBASE
        value: "false"
defaultSidecars:
  syncDAGsPlugins:
    extraEnvVars:
      - name: GIT_SSL_NO_VERIFY
        value: "true"

#extraVolumes:
#  - name: airflow-requirements
#    configMap:
#      name: airflow-requirements
#
#extraVolumeMounts:
#  - mountPath: /bitnami/python/requirements.txt
#    subPath: requirements.txt
#    name: airflow-requirements

dags:
  enabled: true
  repositories:
    - repository: https://gitea.dev-env/MornieOhtar/airflow-dags.git
      branch: master
      name: MornieOhtar-dags
      path: /

plugins:
  enabled: false

triggerer:
  persistence:
    storageClass: rook-system-r3

rbac:
  create: true

metrics:
  enabled: false
  serviceMonitor:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: pg-airflow-rw.automation
  port: 5432
  user: app
  database: app
  existingSecret: pg-airflow-app
  existingSecretPasswordKey: password

setupDBJob:
  enabled: false

redis:
  enabled: false

externalRedis:
  host: redis-cluster-main-master.backend
