auth:
  username: user
  existingSecret: airflow-auth

executor: KubernetesExecutor

image:
  tag: 3.0.2-debian-12-r2

defaultInitContainers:
  loadDAGsPlugins:
    extraEnvVars:
      - name: GIT_SSL_NO_VERIFY
        value: "true"
      - name: GIT_SYNC_PULL
        value: "always"
      - name: GIT_SYNC_REBASE
        value: "false"
defaultSidecars:
  syncDAGsPlugins:
    extraEnvVars:
      - name: GIT_SSL_NO_VERIFY
        value: "true"

#extraVolumes:
#  - name: airflow-requirements
#    configMap:
#      name: airflow-requirements
#
#extraVolumeMounts:
#  - mountPath: /bitnami/python/requirements.txt
#    subPath: requirements.txt
#    name: airflow-requirements

dags:
  enabled: true
  repositories:
    - repository: https://gitea.dev-env/MornieOhtar/airflow-dags.git
      branch: master
      name: mornieohtar
      path: /

plugins:
  enabled: false

extraEnvVars:
  - name: PYTHONPATH
    value: "/opt/bitnami/airflow/dags/git_mornieohtar"
  # IMPORTANT: With this, all dates (i.e. schedules) are treated in local time instead of UTC
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: "Europe/Kyiv"

web:
  automountServiceAccountToken: true
  resourcesPreset: "large"

worker:
  automountServiceAccountToken: true

scheduler:
  automountServiceAccountToken: true

triggerer:
  automountServiceAccountToken: true
  persistence:
    storageClass: rook-system-r3

rbac:
  create: true

metrics:
  enabled: false
  serviceMonitor:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: pg-airflow-rw.automation
  port: 5432
  user: app
  database: app
  existingSecret: pg-airflow-app
  existingSecretPasswordKey: password

setupDBJob:
  enabled: false

redis:
  enabled: false

externalRedis:
  host: redis-cluster-main-master.backend
