apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
spec:
  selector:
    app.kubernetes.io/name: sonarr
  ports:
    - port: 8989
      targetPort: sonarr
      name: sonarr
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              protocol: TCP
              name: sonarr
          volumeMounts:
            - mountPath: /tv
              name: jellyfin-video
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /config
              name: sonarr-config
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: SONARR__APP__INSTANCENAME
              value: Mornery Sonarr
            - name: SONARR__AUTH__APIKEY
              value: <sonarr-api-key>
            - name: SONARR__AUTH__ENABLED
              value: "true"
            - name: SONARR__AUTH__METHOD
              value: FORMS
            - name: SONARR__AUTH__REQUIRED
              value: "true"
            - name: SONARR__LOG__DBENABLED
              value: "false"
            - name: SONARR__POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: pg-sonarr-data-app
                  key: host
            - name: SONARR__POSTGRES__PORT
              value: "5432"
            - name: SONARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: pg-sonarr-data-app
                  key: user
            - name: SONARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-sonarr-data-app
                  key: password
            - name: SONARR__POSTGRES__MAINDB
              valueFrom:
                secretKeyRef:
                  name: pg-sonarr-data-app
                  key: dbname
            - name: SONARR__SERVER__URLBASE
              value: "/"
            - name: SONARR__SERVER__BINDADDRESS
              value: "*"
            - name: SONARR__SERVER__PORT
              value: "8989"
            - name: SONARR__SERVER__ENABLESSL
              value: "False"
            - name: SONARR__SERVER__SSLPORT
              value: "9898"
            - name: SONARR__LOG__LEVEL
              value: "warning"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 750m
              memory: 1Gi
              ephemeral-storage: 256Mi
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-data
        - name: jellyfin-video
          persistentVolumeClaim:
            claimName: jellyfin-media
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-data
