apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-fm-config
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  config.yaml: |
    server:
      baseURL: ""
      database: "/files/database.db"
      sources:
        - path: "/files/shared"
          name: "Shared"
          config:
            indexingInterval: 0
            disabled: false
            defaultUserScope: "/"
            defaultEnabled: false
            createUserDir: false
        - path: "/files/personal"
          name: "Personal"
          config:
            indexingInterval: 0
            disabled: false
            defaultUserScope: "/"
            defaultEnabled: false
            createUserDir: true
      externalUrl: "qfm.<homelab-domain>"
      internalUrl: "quantum-fm.home"
    auth:
      tokenExpirationHours: 2
      methods:
        proxy:
          enabled: false
        noauth: false
        password:
          enabled: false
        oidc:
          enabled: true
          clientId: "<qfm-oidc-client-id>"
          clientSecret: "<qfm-oidc-client-secret>"
          authorizationUrl: "https://keycloak.<homelab-domain>/realms/homelab/protocol/openid-connect/auth"
          tokenUrl: "https://keycloak.<homelab-domain>/realms/homelab/protocol/openid-connect/token"
          userInfoUrl: "https://keycloak.<homelab-domain>/realms/homelab/protocol/openid-connect/userinfo"
          scopes: "openid groups email roles profile"
          userIdentifier: "username"
          jwksUrl: "https://keycloak.<homelab-domain>/realms/homelab/protocol/openid-connect/certs"
    frontend:
      name: "Mornery File Manager"
      disableDefaultLinks: false 
      disableUsedPercentage: false
    userDefaults:
      preview:
        highQuality: false
        image: false
        video: false
        office: false
        popup: false
      stickySidebar: false
      darkMode: false
      lockPassword: false
      disableSettings: false
      locale: ""
      viewMode: ""
      gallerySize: 0
      singleClick: false
      permissions:
        api: false
        admin: false
        modify: true
        share: true
        realtime: false
      showHidden: false
      dateFormat: false
      themeColor: ""
      quickDownload: false
      disableOnlyOfficeExt: ""
