apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum-fm
  labels:
    app: quantum-fm
    use: data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
