deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: true
  name: "traefik"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: HostRegexp(`^dash-traefik\.[a-zA-Z]+\.[a-zA-Z]+\.[a-zA-Z]+$`)
    entryPoints:
      - websecure

providers:
  kubernetesCRD:
    enabled: true
    nativeLBByDefault: true
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: false
  file:
    enabled: false

service:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.245

persistence:
  enabled: true
  size: 256Mi
  accessMode: ReadWriteMany
  storageClass: rook-system-r3

ports:
  external:
    port: 18443
    expose:
      default: true
    exposedPort: 8443
    protocol: TCP

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging server
      httpChallenge:
        entryPoint: web
      storage: /data/acme.json
