apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: technitium-dns
  namespace: operators
  labels:
    release: prometheus-operator
    jobLabel: technitium-dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: technitium-dns
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - path: /metrics
      port: metrics
