###################################################################################################
#
# Uber-Application to be used to deploy all other applications, configured with this setup
#
###################################################################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  project: homelab

  source:
    repoURL: ssh://git@gitea.dev-env:22/MornieOhtar/homelab-argocd.git
    targetRevision: HEAD
    path: app-in-app
    directory:
      recurse: false
      include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
