apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-hl-ssl
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: jellyfin-server-tls
  renewBefore: 240h
  duration: 2160h
  commonName: video.<homelab-domain>
  dnsNames:
    - video.<homelab-domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  # keystores allows adding additional output formats. This is an example for reference only.
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: jellyfin-hl-ssl-pass
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-hl-ssl-pass
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  password: <LE_p12_pass | base64encode>
