apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  annotations:
    external-dns.alpha.kubernetes.io/hostname: video.homelab.local
  name: jellyfin
spec:
  type: LoadBalancer
  loadBalancerClass: homelab-metallb
  externalTrafficPolicy: Local
  ports:
  - port: 443
    targetPort: https
    name: https
  - port: 1900
    targetPort: dlna
    name: dlna
  - port: 7359
    protocol: UDP
    targetPort: clientdiscovery
    name: clientdiscovery
  selector:
    app.kubernetes.io/name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/nas
                    operator: In
                    values:
                      - "nas"
      tolerations:
        - key: "nas"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      containers:
        - name: jellyfin
          image: 'jellyfin/jellyfin:10.10.6'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          ports:
            - containerPort: 8096
              name: http
            - containerPort: 8920
              name: https
            - containerPort: 1900
              name: dlna
            - containerPort: 7359
              protocol: UDP
              name: clientdiscovery
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /cert
              name: tls-cert
            # LIBRARY
            - mountPath: /media
              name: jellyfin-video
            - mountPath: /config
              name: jellyfin-config
            # TEMP
            - mountPath: /cache
              name: jellyfin-cache
            - mountPath: /transcodes
              name: jellyfin-transcodes
            # VIDEO
            - mountPath: /dev/dri
              name: jellyfin-dri
      volumes:
        - name: tls-cert
          secret:
            secretName: jellyfin-server-tls
        # LIBRARY
        - name: jellyfin-video
          hostPath:
            path: <NFS_STOR_0_PATH>/multimedia/video/
            type: Directory
        # CONFIG
        - name: jellyfin-config
          hostPath:
            path: <NFS_STOR_0_PATH>/system/jellyfin
            type: Directory
        # TEMP
        - name: jellyfin-cache
          emptyDir: {}
        - name: jellyfin-transcodes
          emptyDir: {}
        # VIDEO
        - name: jellyfin-dri
          hostPath:
            path: /dev/dri

