apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  annotations:
    external-dns.alpha.kubernetes.io/hostname: video.homelab.local
  name: jellyfin
spec:
  type: LoadBalancer
  loadBalancerClass: homelab-metallb
  ports:
  - port: 443
    targetPort: https
    name: https
  - port: 1900
    targetPort: dlna
    name: dlna
  - port: 7359
    protocol: UDP
    targetPort: clientdiscovery
    name: clientdiscovery
  selector:
    app.kubernetes.io/name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: 'jellyfin/jellyfin:10.10.6'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          ports:
            - containerPort: 8096
              name: http
            - containerPort: 8920
              name: https
            - containerPort: 1900
              name: dlna
            - containerPort: 7359
              protocol: UDP
              name: clientdiscovery
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /cert
              name: tls-cert
            # LIBRARY
            - mountPath: /media
              name: jellyfin-video
            - mountPath: /config
              name: jellyfin-config
            # TEMP
            - mountPath: /cache
              name: jellyfin-cache
            - mountPath: /transcodes
              name: jellyfin-transcodes
            # VIDEO
            - mountPath: /dev/mali0
              name: jellyfin-mali0
            - mountPath: /dev/dri
              name: jellyfin-dri
            - mountPath: /dev/mpp_service
              name: jellyfin-mpp-service
            - mountPath: /dev/dma_heap
              name: jellyfin-dma-heap
            - mountPath: /dev/rga
              name: jellyfin-rga
      volumes:
        - name: tls-cert
          secret:
            secretName: jellyfin-server-tls
        # LIBRARY
        - name: jellyfin-video
          nfs:
            server: <NFS_STOR_0_SERVER>
            path: <NFS_STOR_0_PATH>/multimedia/video/
        # CONFIG
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        # TEMP
        - name: jellyfin-cache
          emptyDir: {}
        - name: jellyfin-transcodes
          emptyDir: {}
        # VIDEO
        - name: jellyfin-mali0
          hostPath:
            path: /dev/mali0
        - name: jellyfin-dri
          hostPath:
            path: /dev/dri
        - name: jellyfin-mpp-service
          hostPath:
            path: /dev/mpp_service
        - name: jellyfin-dma-heap
          hostPath:
            path: /dev/dma_heap
        - name: jellyfin-rga
          hostPath:
            path: /dev/rga

