apiVersion: v1
kind: Service
metadata:
  labels:
    application.name: audiobookshelf
  name: audiobookshelf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: audiobookshelf
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      automountServiceAccountToken: false
      containers:
        - name: audiobookshelf
          image: 'ghcr.io/advplyr/audiobookshelf:2.18.1'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: abs-config
            - mountPath: /metadata
              name: abs-metadata
            - mountPath: /audiobooks
              name: abs-audiobooks
            - mountPath: /podcasts
              name: abs-podcasts
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
      volumes:
        - name: abs-config
          persistentVolumeClaim:
            claimName: abs-config
        - name: abs-metadata
          persistentVolumeClaim:
            claimName: abs-metadata
        - name: abs-audiobooks
          nfs:
            server: <NFS_STOR_0_SERVER>
            path: <NFS_STOR_0_PATH>/multimedia/audiobooks
        - name: abs-podcasts
          nfs:
            server: <NFS_STOR_0_SERVER>
            path: <NFS_STOR_0_PATH>/multimedia/podcasts
