apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-config
  labels:
    app: audiobookshelf
    use: config
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-metadata
  labels:
    app: audiobookshelf
    use: data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  labels:
    app: audiobookshelf
    use: media
spec:
  storageClassName: rook-media-r1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  labels:
    app: audiobookshelf
    use: media
spec:
  storageClassName: rook-media-r1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
