apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: argo-events-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    home-ns:
      port: "12000"
      endpoint: /home
      method: POST
