apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
      path: "backend/argocd"
      directory:
        recurse: true
        include: "*.yaml"
        exclude: 'values.yaml'
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.7.16
      chart: argo-cd
      helm:
        valueFiles:
          - $homelab/backend/argocd/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true # For ArgoCD to properly manage himself it is safer to sync only changed resources
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
