apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
spec:
  project: homelab

  source:
    repoURL: ssh://git@gitea.dev-env:22/MornieOhtar/homelab-argocd.git
    targetRevision: HEAD
    path: backend/ntfy

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - kind: Secret
      name: "csi-node-driver"
      jsonPointers:
        - /data
        - /data/ca.crt
        - /data/namespace
        - /data/token
