apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster-main
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: registry-1.docker.io/bitnamicharts
      path: redis
      targetRevision: 20.6.3
      chart: redis
      helm:
        valueFiles:
          - $homelab/backend/redis/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
