apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-storage
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      path: backend/rook
    - repoURL: ssh://git@gitea.dev-env:22/MornieOhtar/homelab-argocd.git
      targetRevision: HEAD
      path: personal/s3

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - kind: ObjectBucketClaim
      group: objectbucket.io
      jsonPointers:
        - /metadata/labels
