apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: homelab

  sources:
    - repoURL: ssh://git@gitea.dev-env:22/MornieOhtar/homelab-argocd.git
      targetRevision: HEAD
      ref: homelab
      path: 'backend/traefik'
      directory:
        recurse: true
        include: '*.yaml'
        exclude: 'values.yaml'
    - repoURL: https://traefik.github.io/charts
      targetRevision: 37.0.0
      chart: traefik
      helm:
        valueFiles:
          - $homelab/backend/traefik/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
