image:
  tag: v0.10.9

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

config:
  useExistingConfigMap: homepage-config

env:
  TZ: Europe/Kyiv
  PASSWD:
    valueFrom:
      secretKeyRef:
        name: homepage
        key: password
