apiVersion: v1
kind: Secret
metadata:
  name: k8up-local-minio
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <K8UP_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <K8UP_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: k8up-local-restic
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  restic-password: <k8up-local-restic>
