apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-whitelist
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.30.0/23
      - 10.0.0.0/8
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: default
spec:
  insecureSkipVerify: true
  disableHTTP2: false
