apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  selector:
    app.kubernetes.io/name: radarr
  ports:
    - port: 7878
      targetPort: radarr
      name: radarr
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
        - name: radarr
          image: linuxserver/radarr:5.22.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
              protocol: TCP
              name: radarr
          volumeMounts:
            - mountPath: /movies
              name: jellyfin-video
            - mountPath: /library/anime
              name: media-anime
              subPath: movies
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /config
              name: radarr-config
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: RADARR__APP__INSTANCENAME
              value: Mornery Radarr
            - name: RADARR__AUTH__APIKEY
              value: <radarr-api-key>
            - name: RADARR__AUTH__ENABLED
              value: "true"
            - name: RADARR__AUTH__METHOD
              value: Forms
            - name: RADARR__AUTH__REQUIRED
              value: "true"
            - name: RADARR__LOG__DBENABLED
              value: "false"
            - name: RADARR__POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: pg-radarr-app
                  key: host
            - name: RADARR__POSTGRES__PORT
              value: "5432"
            - name: RADARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: pg-radarr-app
                  key: user
            - name: RADARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-radarr-app
                  key: password
            - name: RADARR__POSTGRES__MAINDB
              valueFrom:
                secretKeyRef:
                  name: pg-radarr-app
                  key: dbname
            - name: RADARR__SERVER__URLBASE
              value: "/"
            - name: RADARR__SERVER__BINDADDRESS
              value: "*"
            - name: RADARR__SERVER__PORT
              value: "7878"
            - name: RADARR__SERVER__ENABLESSL
              value: "False"
            - name: RADARR__SERVER__SSLPORT
              value: "9898"
            - name: RADARR__LOG__LEVEL
              value: "warning"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 750m
              memory: 1Gi
              ephemeral-storage: 256Mi
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-data
        - name: jellyfin-video
          persistentVolumeClaim:
            claimName: jellyfin-media
        - name: media-anime
          persistentVolumeClaim:
            claimName: media-anime
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-data
