apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-home
spec:
  project: homelab

  source:
    repoURL: https://github.com/MornieOhtar/homelab.git
    targetRevision: HEAD
    path: home/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: home

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
