apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-lidarr
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-main
    major: 17
  monitoring:
    enablePodMonitor: true

  # Create PVC templates on local storage for each Postgres pod
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: local-path
      volumeMode: Filesystem

  # Import existing database
  bootstrap:
    recovery:
      source: pg-lidarr

  # Backup strategy
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ceph-local

  # WAL backup clusters
  externalClusters:
    - name: pg-lidarr
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ceph-local
          serverName: pg-lidarr

  # Force Postgres to be running each instance on separate node
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-lidarr-local-schedule
spec:
  schedule: "0 22 */12 * * *" # For local store - backup every hour
  backupOwnerReference: self
  cluster:
    name: pg-lidarr
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
