apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  selector:
    app.kubernetes.io/name: lidarr
  ports:
    - port: 8686
      targetPort: lidarr
      name: lidarr
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
        - name: lidarr
          image: linuxserver/lidarr:2.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
              protocol: TCP
              name: lidarr
          volumeMounts:
            - mountPath: /music
              name: music
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /config
              name: lidarr-config
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: LIDARR__APP__INSTANCENAME
              value: Mornery Lidarr
            - name: LIDARR__AUTH__ENABLED
              value: "True"
            - name: LIDARR__AUTH__METHOD
              value: Forms
            - name: LIDARR__AUTH__REQUIRED
              value: "True"
            - name: LIDARR__LOG__DBENABLED
              value: "false"
            - name: LIDARR__POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: pg-lidarr-app
                  key: host
            - name: LIDARR__POSTGRES__PORT
              value: "5432"
            - name: LIDARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: pg-lidarr-app
                  key: user
            - name: LIDARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-lidarr-app
                  key: password
            - name: LIDARR__POSTGRES__MAINDB
              valueFrom:
                secretKeyRef:
                  name: pg-lidarr-app
                  key: dbname
            - name: LIDARR__SERVER__URLBASE
              value: "/"
            - name: LIDARR__SERVER__BINDADDRESS
              value: "*"
            - name: LIDARR__SERVER__PORT
              value: "8686"
            - name: LIDARR__SERVER__ENABLESSL
              value: "False"
            - name: LIDARR__SERVER__SSLPORT
              value: "9898"
            - name: LIDARR__LOG__LEVEL
              value: "warning"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 750m
              memory: 1Gi
              ephemeral-storage: 256Mi
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-data
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-data
