apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
    jobLabel: tekton-overview
  name: tekton-overview
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http-metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - tekton-pipelines
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/part-of: tekton-pipelines
