###################################################################################################
#
# Automations-related applications
#
###################################################################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation
spec:
  project: homelab

  source:
    repoURL: https://github.com/MornieOhtar/homelab.git
    targetRevision: HEAD
    path: automation
    directory:
      recurse: false
      include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
