apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bar-salt-rim
  name: bar-salt-rim
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: bar-salt-rim
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-salt-rim
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
  labels:
    app.kubernetes.io/name: bar-salt-rim
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bar-salt-rim
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bar-salt-rim
    spec:
      automountServiceAccountToken: false
      containers:
        - name: salt-rim
          image: barassistant/salt-rim:3.9.1
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: https://bar.<homelab-domain>/bar
            - name: MEILISEARCH_URL
              value: https://bar.<homelab-domain>/search
            - name: BAR_NAME
              value: Owl's bar
            - name: DESCRIPTION
              value: Owl's bar
            - name: DEFAULT_LOCALE
              value: en_US
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 128Mi
          ports:
            - containerPort: 8080
