apiVersion: v1
kind: Service
metadata:
  labels:
    application.name: barassistant
  name: barassistant
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: barassistant
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barassistant
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barassistant
  template:
    metadata:
      labels:
        app: barassistant
    spec:
      automountServiceAccountToken: false
      containers:
        - name: barassistant
          image: 'barassistant/server:4.3.2'
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_URL
              value: https://bar.<homelab-domain>/bar
            - name: LOG_CHANNEL
              value: stderr
            - name: MEILISEARCH_KEY
              value: <barassistant-meili-master-key>
            - name: MEILISEARCH_HOST
              value: http://bar-meili:7700
            - name: REDIS_HOST
              value: redis-cluster-main-master.backend
            - name: CACHE_DRIVER
              value: redis
            - name: SESSION_DRIVER
              value: redis
            - name: ALLOW_REGISTRATION
              value: "false"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 128Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www/cocktails/storage/bar-assistant
              name: bar-data
      volumes:
        - name: bar-data
          persistentVolumeClaim:
            claimName: barassistant-data
