apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barassistant-data
  labels:
    app: barassistant
    use: data
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barassistant-data-meili
  labels:
    app: barassistant
    use: meili
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
