apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barassistant-data
  labels:
    app: barassistant
    use: data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barassistant-meili
  labels:
    app: barassistant
    use: meili
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
