crds:
  install: true
  keep: true

workflow:
  serviceAccount:
    create: true
  rbac:
    agentPermissions: true

controller:
  metricsConfig:
    enabled: true
  persistence:
    nodeStatusOffLoad: false
    archive: true
    postgresql:
      host: pg-argo-workflows-rw
      database: app
      tableName: argo_workflows
      userNameSecret:
        name: pg-argo-workflows-app
        key: user
      passwordSecret:
        name: pg-argo-workflows-app
        key: password
      ssl: false
  telemetryConfig:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: operators
  workflowWorkers: 64
  workflowTTLWorkers: 8
  workflowNamespaces:
    - dev-env
    - home

server:
  authModes:
    - server
