apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-pass
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  db: <keycloak-db-name>
  host: <keycloak-db-host>
  port: <keycloak-db-port>
  pwd: <keycloak-db-user>
  user: <keycloak-db-password>
