kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow-requirements
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  requirements.txt: |-
    apache-airflow-providers-apache-kafka
