apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-kube-manager
  namespace: automation
  annotations:
    replicator.v1.mittwald.de/replicate-to: "automation,dev-env,home,backend"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-kube-manager
rules:
  # Allow scaling of StatefulSets
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale", "deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update", "create"]

  # Allow annotating 'cluster.postgresql.cnpg.io'
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "patch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-kube-manager-binding
subjects:
  - kind: ServiceAccount
    name: airflow-kube-manager
    namespace: automation
  - kind: ServiceAccount
    name: airflow-kube-manager
    namespace: dev-env
  - kind: ServiceAccount
    name: airflow-kube-manager
    namespace: home
  - kind: ServiceAccount
    name: airflow-kube-manager
    namespace: backend
roleRef:
  kind: ClusterRole
  name: airflow-kube-manager
  apiGroup: rbac.authorization.k8s.io
