apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-kube-manager
  namespace: automation
  annotations:
    replicator.v1.mittwald.de/replicate-to: "automation,dev-env,home,backend"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-kube-manager
  namespace: automation
  annotations:
    replicator.v1.mittwald.de/replicate-to: "automation,dev-env,home,backend"
rules:
  # Allow scaling of StatefulSets
  - apiGroups: [""]
    resources: ["statefulsets"]
    verbs: ["get", "list", "patch", "update", "create"]

  # Allow annotating 'cluster.postgresql.cnpg.io'
  - apiGroups: ["cluster.postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "patch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-kube-manager-binding
  namespace: automation
  annotations:
    replicator.v1.mittwald.de/replicate-to: "automation,dev-env,home,backend"
subjects:
  - kind: ServiceAccount
    name: airflow-kube-manager
roleRef:
  kind: Role
  name: airflow-kube-manager
  apiGroup: rbac.authorization.k8s.io
