apiVersion: v1
kind: Secret
metadata:
  name: airflow-auth
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  airflow-password: <airflow-password | base64encode>
  airflow-fernet-key: <airflow-fernet-key | base64encode>
  airflow-secret-key: <airflow-secret-key | base64encode>
  airflow-jwt-secret-key: <airflow-secret-key | base64encode>
