kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-machine-learning-cache
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: machine-learning
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "local-path"