apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/service: immich-server
    app.kubernetes.io/name: immich
spec:
  type: ClusterIP
  ports:
    - port: 2283
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: immich
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/name: immich
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
    spec:
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.135.3
          imagePullPolicy: IfNotPresent
          env:
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-immich-app
                  key: dbname
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: pg-immich-app
                  key: host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-immich-app
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-immich-app
                  key: user
            - name: REDIS_HOSTNAME
              value: redis-cluster-main-master.backend
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 2000m
              memory: 4Gi
              ephemeral-storage: 256Mi
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich
