apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: rook-ceph
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: automation
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: backend
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: dev-env
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: home
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: monitoring
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-local-s3
  namespace: operators
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
