apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-creds
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
  REMOTE_KEY_ID: <CNPG_S3_KEY_ID | base64encode>
  REMOTE_SECRET_KEY: <CNPG_S3_SECRET | base64encode>
  REMOTE_URL: <S3_ENDPOINT | base64encode>
  REMOTE_BUCKET_NAME: <CNPG_S3_BUCKET | base64encode>
