crds:
  install: true
  keep: true

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: operators
      selector:
        prometheus: prometheus-operator

webhook:
  enabled: true
