apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-hl-ssl
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: harbor-server-tls
  renewBefore: 240h
  duration: 2160h
  commonName: harbor.<homelab-domain>
  dnsNames:
    - harbor.<homelab-domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
