apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-registry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <NFS_N0_PATH>/system/harbor/registry
    server: <NFS_STOR_0_SERVER>
