apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  secretKey: <harbor-encryption-key | base64encode>
  adminPassword: <harbor-admin-password | base64encode>
