apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
    use: config
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
