apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    # Get Homepage configuration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Electronic books
    gethomepage.dev/group: Home
    gethomepage.dev/icon: calibre-web.png
    gethomepage.dev/name: Calibre
    gethomepage.dev/widget.type: "calibreweb"
    gethomepage.dev/widget.url: "http://calibre:8083"
    gethomepage.dev/widget.username: "<path:kv/data/homepage#calibre-username>"
    gethomepage.dev/widget.password: "<path:kv/data/homepage#calibre-password>"
spec:
  ingressClassName: nginx
  rules:
    - host: books.<homelab-domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre
                port:
                  number: 8083
  tls:
    - hosts:
        - books.<homelab-domain>
      secretName: "books.<homelab-domain>-cert"
