apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  labels:
    app: calibre-web
    use: config
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-db
  labels:
    app: calibre-web
    use: db
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
