apiVersion: v1
kind: Service
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tekton.homelab.local
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 9097
      protocol: TCP
      targetPort: 9097
    - name: http-ui
      port: 80
      protocol: TCP
      targetPort: 9097
