apiVersion: s3.onyxia.sh/v1alpha1
kind: Bucket
metadata:
  name: mimir-blocks
spec:
  # Bucket name (on S3 server, as opposed to the name of the CR)
  name: mimir-blocks

  # Quota to set on the bucket, in bytes (so 1000000000 would be 1GB).
  quota:
    default: 1000000000000 # 1TB
---
apiVersion: s3.onyxia.sh/v1alpha1
kind: Bucket
metadata:
  name: mimir-alertmanager
spec:
  # Bucket name (on S3 server, as opposed to the name of the CR)
  name: mimir-alertmanager

  # Quota to set on the bucket, in bytes (so 1000000000 would be 1GB).
  quota:
    default: 1000000000000 # 1TB
---
apiVersion: s3.onyxia.sh/v1alpha1
kind: Bucket
metadata:
  name: mimir-ruler
spec:
  # Bucket name (on S3 server, as opposed to the name of the CR)
  name: mimir-ruler

  # Quota to set on the bucket, in bytes (so 1000000000 would be 1GB).
  quota:
    default: 1000000000000 # 1TB
