apiVersion: v1
kind: Secret
metadata:
  name: external-dns-technitium
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  tsig-key: <external-dns-tsig-key | base64encode>
  tsig-keyname: <external-dns-tsig-keyname | base64encode>
  tsig-secret-alg: <external-dns-tsig-alg | base64encode>
  zone: <homelab-domain | base64encode>
