apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: intel-gpu
spec:
  allowCrossNamespaceImport: true
  resyncPeriod: 30s
  folder: 'Cluster'
  instanceSelector:
    matchLabels:
      dashboards: "grafana-cluster-main"
  grafanaCom:
    id: 23251
  datasources:
    - inputName: "DS_PROMETHEUS-NAS"
      datasourceName: "mimir"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: intel-gpu-exporter
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-exporter
  jobLabel: job-label
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: intel-gpu-exporter
        job-label: intel-gpu
    spec:
      containers:
        - name: exporter
          image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
          resources:
            requests:
              gpu.intel.com/i915_monitoring: "1"
            limits:
              gpu.intel.com/i915_monitoring: "1"
          ports:
            - name: metrics
              containerPort: 8080
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
