global:
  namespace: backend

injector:
  metrics:
    enabled: true

server:
  dataStorage:
    enabled: false
  volumes:
    - name: vault-data
      persistentVolumeClaim:
        claimName: hashicorp-vault-data
  volumeMounts:
    - mountPath: /vault/data
      name: vault-data

ui:
  enabled: true

serverTelemetry:
  serviceMonitor:
    enabled: true
