apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-cluster-main-backup
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
  labels:
    type: nfs
    app: postgres-cluster-main
    use: backup
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS_STOR_0_SERVER>
    path: <NFS_STOR_0_PATH>/backup/postgres-cluster-main
