apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cluster-main-backup
  labels:
    app: postgres-cluster-main
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: postgres-cluster-main
      use: backup
