apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  labels:
    app: paperless
    use: data
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  labels:
    app: paperless
    use: media
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  labels:
    app: paperless
    use: export
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  labels:
    app: paperless
    use: consume
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
