auth:
  enabled: false

master:
  count: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 1Gi

replica:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 1Gi

metrics:
  enabled: false
