apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-b2-backup
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  schedule: 0 6 * * *
  timeZone: Europe/Kyiv
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: gitea-b2-backup-restic
              image: restic/restic:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - '-c'
              args:
                - |
                  restic backup /data --group-by paths
              env:
                - name: RESTIC_REPOSITORY
                  value: <restic-gitea-url>
                - name: RESTIC_PASSWORD
                  value: <restic-gitea-password>
                - name: AWS_ACCESS_KEY_ID
                  value: <restic-gitea-key-id>
                - name: AWS_SECRET_ACCESS_KEY
                  value: <restic-gitea-key-secret>
                - name: AWS_DEFAULT_REGION
                  value: <restic-s3-region>
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              nfs:
                server: <NFS_STOR_0_SERVER>
                path: <NFS_STOR_0_PATH>/system/gitea
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
