apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gitea
  name: gitea
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    external-dns.alpha.kubernetes.io/hostname: git.homelab.local
spec:
  ports:
    - port: 443
      targetPort: web
      name: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gitea
          image: 'gitea/gitea:1.23.3'
          imagePullPolicy: IfNotPresent
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              valueFrom:
                secretKeyRef:
                  name: pg-gitea-app
                  key: host
            - name: GITEA__database__NAME
              valueFrom:
                secretKeyRef:
                  name: pg-gitea-app
                  key: dbname
            - name: GITEA__database__USER
              valueFrom:
                secretKeyRef:
                  name: pg-gitea-app
                  key: user
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: pg-gitea-app
                  key: password
            - name: GITEA__server__DISABLE_SSH
              value: "true"
            - name: GITEA__server__CERT_FILE
              value: "/cert/tls.crt"
            - name: GITEA__server__KEY_FILE
              value: "/cert/tls.key"
            - name: GITEA__server__PROTOCOL
              value: "https"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 1000m
              memory: 512Mi
              ephemeral-storage: 1Gi
          ports:
            - containerPort: 3000
              name: web
          volumeMounts:
            - mountPath: /data
              name: gitea-data
            - mountPath: /cert
              name: tls-cert
      volumes:
        - name: gitea-data
          nfs:
            server: <NFS_STOR_0_SERVER>
            path: <NFS_STOR_0_PATH>/system/gitea
        - name: tls-cert
          secret:
            secretName: gitea-server-tls
