apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-root
spec:
  name: .rgw.root
  deviceClass: ssd
  enableCrushUpdates: true
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    pg_num: "8"
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-meta-pool
spec:
  deviceClass: ssd
  enableCrushUpdates: true
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    pg_num: "8"
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-data-pool-ssd-ec-2-1
spec:
  deviceClass: ssd
  enableCrushUpdates: true
  failureDomain: osd
  erasureCoded:
    # For production it is recommended to use more chunks, such as 4+2 or 8+4
    dataChunks: 2
    codingChunks: 1
  parameters:
    bulk: "true"
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: backup-ssd
spec:
  sharedPools:
    metadataPoolName: rgw-meta-pool
    dataPoolName: rgw-data-pool-ssd-ec-2-1
    preserveRadosNamespaceDataOnDelete: true
  gateway:
    # sslCertificateRef:
    port: 80
    instances: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-backup-ssd-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
parameters:
  objectStoreName: backup-ssd
  objectStoreNamespace: rook-ceph
