apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cf-issuer
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <cert-manager-email>
    privateKeySecretRef:
      name: cf-issuer
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
