apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-cert
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: homelab-cert
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "automation,argo-cd,dev-env,home,operators,rook-ceph"
  issuerRef:
    name: cf-issuer
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: homelab-ssl-pass
  commonName: '*.<homelab-domain>'
  dnsNames:
    - "*.<homelab-domain>"
---
apiVersion: v1
kind: Secret
metadata:
  name: homelab-ssl-pass
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  password: <dns_p12_pass | base64encode>
