apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <cert-manager-email>
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
