expose:
  type: loadBalancer
  tls:
    enable: true
    certSource: secret
    secret:
      secretName: harbor-server-tls
  loadBalancer:
    name: harbor
    annotations:
      external-dns.alpha.kubernetes.io/hostname: harbor.homelab.local

externalURL: harbor.homelab.local

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry-nfs"
    jobservice:
      jobLog:
        existingClaim: "harbor-job-log-nfs"
    trivy:
      existingClaim: "harbor-trivy-nfs"
  imageChartStorage:
    type: filesystem

database:
  type: external
  external:
    host: pg-harbor-rw
    port: 5432
    username: app
    coreDatabase: app
    existingSecret: pg-harbor-app

internalTLS:
  enabled: true
  strong_ssl_ciphers: true
  certSource: auto

existingSecretAdminPassword: harbor-secret
existingSecretAdminPasswordKey: adminPassword

existingSecretSecretKey: harbor-secret

redis:
  type: external
  external:
    addr: redis-cluster-main-master.backend

ipFamily:
  ipv6:
    enabled: false
  ipv4:
    enabled: true

metrics:
  enabled: true
  serviceMonitor:
    create: true
    additionalLabels:
      release: prometheus-operator

# Tolerations to start on amd64 node, as other nodes platform not supported
portal:
  nodeSelector:
    kubernetes.io/arch: amd64
core:
  nodeSelector:
    kubernetes.io/arch: amd64
jobservice:
  nodeSelector:
    kubernetes.io/arch: amd64
registry:
  nodeSelector:
    kubernetes.io/arch: amd64
trivy:
  nodeSelector:
    kubernetes.io/arch: amd64
exporter:
  nodeSelector:
    kubernetes.io/arch: amd64
nginx:
  nodeSelector:
    kubernetes.io/arch: amd64
