kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/opt/local-path-provisioner"]
        },
        {
          "node":"nas001.<NODES_DOMAIN>",
          "paths":["<NFS_N0_PATH>/local-path-provisioner"]
        },
        {
          "node":"n001.homelab",
          "paths":["/data/local"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper-pod
          image: busybox
          imagePullPolicy: IfNotPresent
