controller:
  name: nginx-int
  hostNetwork: false

  ingressClass: nginx-internal
  ingressClassByName: true
  ingressClassResource:
    controllerValue: k8s.io/ingress-nginx-internal
    name: nginx-internal
    enabled: true
    default: false


  enableCertManager: false

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.30.241
    ipFamilies:
      - IPv4

  kind: DaemonSet
  resources:
    requests:
      cpu: 100m
      memory: 150m

prometheus:
  create: false
