
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: graphana-mimir
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana-cluster-main"
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    database: prometheus
    jsonData:
      timeInterval: 10s
      tlsSkipVerify: true
    name: mimir
    type: prometheus
    url: http://grafana-mimir-gateway/prometheus
