apiVersion: projectcalico.org/v3
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  healthChecks: Enabled
  etcdV3CompactionPeriod: 10m0s
  prometheusMetricsPort: 9094
  controllers:
    node:
      reconcilerPeriod: 5m0s
      leakGracePeriod: 15m0s
      syncLabels: Enabled
      hostEndpoint:
        autoCreate: Disabled
    policy:
      reconcilerPeriod: 5m0s
    workloadEndpoint:
      reconcilerPeriod: 5m0s
    serviceAccount:
      reconcilerPeriod: 5m0s
    namespace:
      reconcilerPeriod: 5m0s
