apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: csi-node-driver
  namespace: calico-system
  annotations:
    kubernetes.io/service-account.name: csi-node-driver
data: {}
