apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: k8up-schedule-operators-local
spec:
  backend:
    s3:
      endpoint: http://minio.backend:9000
      bucket: k8up-operators
      accessKeyIDSecretRef:
        name: k8up-operators-local-minio
        key: accessKey
      secretAccessKeySecretRef:
        name: k8up-operators-local-minio
        key: secretKey
    repoPasswordSecretRef:
      name: k8up-local-restic
      key: restic-password
  backup:
    schedule: '0 */2 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    promURL: http://prometheus-pushgateway.operators:9091
  check:
    schedule: '@daily-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    promURL: http://prometheus-pushgateway.operators:9091
  prune:
    schedule: '@daily-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    retention:
      keepLast: 12
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 12
      keepYearly: 100
