apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-executor
  namespace: dev-env
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-executor
  namespace: home
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-executor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-executor
subjects:
  - kind: ServiceAccount
    name: argo-workflows-executor
    namespace: dev-env
  - kind: ServiceAccount
    name: argo-workflows-executor
    namespace: home
