apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-workflow.service-account-token
  namespace: dev-env
  annotations:
    kubernetes.io/service-account.name: argo-workflow
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-workflow.service-account-token
  namespace: home
  annotations:
    kubernetes.io/service-account.name: argo-workflow
