apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-admin
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-admin
subjects:
  - kind: ServiceAccount
    name: argo-admin
    namespace: dev-env
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-admin.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-admin
