apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  labels:
    app: mealie
    use: data
  annotations:
    'k8up.io/backup': 'true'
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
