apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  labels:
    app: mealie
    use: data
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
