initdb:
  image:
    tag: 16
  resources:
    requests:
      memory: "200Mi"
    limits:
      memory: "1Gi"

extraVolumes:
  - name: openproject-temp
    emptyDir:
      sizeLimit: 1Gi
  - name: openproject-sys-temp
    emptyDir:
      sizeLimit: 1Gi

extraVolumeMounts:
  - mountPath: /app/tmp
    name: openproject-temp
  - mountPath: /tmp
    name: openproject-sys-temp

ingress:
  enabled: false

openproject:
  useTmpVolumes: false

persistence:
  enabled: false # Store data in S3 bucket

s3:
  enabled: true
  auth:
    existingSecret: "openproject-minio"
  secretKeys:
    accessKeyId: "accessKey"
    secretAccessKey: "secretKey"
  bucketName: openproject
  endpoint: "s3:http://minio.backend:9000/openproject"

postgresql:
  bundled: false
  connection:
    host: "pg-openproject-rw"
    port: "5432"
  auth:
    existingSecret: "pg-openproject-app"
    secretKeys:
      adminPasswordKey: "password"
      userPasswordKey: "password"
    username: "app"
    database: "app"

# Do not use builtin job deletion, as ArgoCD will report descrepancy
# for resource. Use ArgoCD hook instead
cleanup:
  deletePodsOnSuccess: false
