initdb:
  image:
    tag: 16
  resources:
    requests:
      memory: "200Mi"
    limits:
      memory: "1Gi"

ingress:
  enabled: false

openproject:
  useTmpVolumes: true

persistence:
  enabled: false # Store data in S3 bucket

s3:
  enabled: true
  auth:
    existingSecret: "openproject-minio"
  secretKeys:
    accessKeyId: "accessKey"
    secretAccessKey: "secretKey"
  bucketName: openproject
  endpoint: "s3:http://minio.backend:9000/openproject"

containerSecurityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  runAsNonRoot: false

postgresql:
  bundled: false
  connection:
    host: "pg-openproject-rw"
    port: "5432"
  auth:
    existingSecret: "pg-openproject-app"
    secretKeys:
      adminPasswordKey: "password"
      userPasswordKey: "password"
    username: "app"
    database: "app"

# Do not use builtin job deletion, as ArgoCD will report descrepancy
# for resource. Use ArgoCD hook instead
cleanup:
  deletePodsOnSuccess: false
