apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-hl-ssl
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: nexus-server-tls
  renewBefore: 240h
  duration: 2160h
  commonName: nexus.<homelab-domain>
  dnsNames:
    - nexus.<homelab-domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: nexus-hl-ssl-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-hl-ssl-pass
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
data:
  password: <nexus_p12_pass | base64encode>
