apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torrent-hl-ssl
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  secretName: torrent-server-tls
  renewBefore: 240h
  duration: 2160h
  commonName: torrent.<homelab-domain>
  dnsNames:
    - torrent.<homelab-domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
