apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    metallb.universe.tf/loadBalancerIPs: 192.168.30.230
    external-dns.alpha.kubernetes.io/hostname: torrent.homelab.local
    # Get Homepage configuration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Torrent client
    gethomepage.dev/group: Home
    gethomepage.dev/icon: qbittorrent.png
    gethomepage.dev/name: QBittorrent
    gethomepage.dev/href: https://torrent.<homelab-domain>
    gethomepage.dev/widget.type: "qbittorrent"
    gethomepage.dev/widget.url: "http://qbittorrent"
    gethomepage.dev/widget.username: "<path:kv/data/homepage#qbittorrent-login>"
    gethomepage.dev/widget.password: "<path:kv/data/homepage#qbittorrent-pass>"
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: webui
      name: webui
      protocol: TCP
    - port: 6881
      targetPort: torrent-tcp
      name: torrent-tcp
      protocol: TCP
    - port: 6881
      targetPort: torrent-udp
      name: torrent-udp
      protocol: UDP
    - port: 17871
      targetPort: metrics
      name: metrics
      protocol: TCP
    - port: 9117
      targetPort: jackett
      name: jackett
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app.kubernetes.io/name: jackett
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - port: 9117
      targetPort: jackett
      name: jackett
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/nas
                    operator: In
                    values:
                      - "nas"
      tolerations:
        - key: "nas"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      containers:
        - name: torrent
          image: lscr.io/linuxserver/qbittorrent:5.0.3-r0-ls376
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: webui
            - containerPort: 6881
              protocol: TCP
              name: torrent-tcp
            - containerPort: 6881
              protocol: UDP
              name: torrent-udp
          volumeMounts:
            - mountPath: /cert
              name: tls-cert
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /config
              name: qbittorrent-config
        - name: jackett
          image: lscr.io/linuxserver/jackett:v0.22.1316-ls659
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9117
              protocol: TCP
              name: jackett
          volumeMounts:
            - mountPath: /config
              name: jackett-config
          env:
            - name: TZ
              value: Europe/Kyiv
        - name: exporter
          image: caseyscarborough/qbittorrent-exporter:v1.3.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 17871
              protocol: TCP
              name: metrics
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: QBITTORRENT_BASE_URL
              value: <qbittorrent-base-url>
            - name: QBITTORRENT_USERNAME
              value: <qbittorrent-username>
            - name: QBITTORRENT_PASSWORD
              value: <qbittorrent-password>
      volumes:
        - name: qbittorrent-config
          hostPath: # Torrent generally recommends using locally-attached volumes
            path: <NFS_STOR_0_PATH>/system/qbittorrent/ # Specify a path to a local drive or volume on the Kubernetes worker node
            type: Directory # The path to the last directory must exist
        - name: jackett-config
          hostPath: # Torrent generally recommends using locally-attached volumes
            path: <NFS_STOR_0_PATH>/system/jackett/ # Specify a path to a local drive or volume on the Kubernetes worker node
            type: Directory # The path to the last directory must exist
        - name: qbittorrent-downloads
          hostPath: # Torrent generally recommends using locally-attached volumes
            path: <NFS_STOR_0_PATH>/multimedia/torrent/ # Specify a path to a local drive or volume on the Kubernetes worker node
            type: Directory # The path to the last directory must exist
        - name: tls-cert
          secret:
            secretName: torrent-server-tls
