apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16,10.0.0.0/8
    cert-manager.io/cluster-issuer: letsencrypt-production
    # Get Homepage configuration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Torrent proxy
    gethomepage.dev/group: Home
    gethomepage.dev/icon: jackett.png
    gethomepage.dev/name: Jackett
    gethomepage.dev/pod-selector: app.kubernetes.io/name=qbittorrent
    gethomepage.dev/widget.type: "jackett"
    gethomepage.dev/widget.url: "http://qbittorrent:9117"
    gethomepage.dev/widget.password: "<path:kv/data/homepage#jackett-pass>"
spec:
  ingressClassName: nginx
  rules:
    - host: jackett.<homelab-domain>
      http:
        paths:
          - path: /
            backend:
              service:
                name: qbittorrent
                port:
                  name: jackett
            pathType: Prefix
  tls:
    - hosts:
        - jackett.<homelab-domain>
      secretName: "jackett.<homelab-domain>-cert"
