apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  labels:
    app: jackett
    use: config
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  labels:
    app: qbittorrent
    use: config
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: rook-system-r3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
