apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.100
    external-dns.alpha.kubernetes.io/hostname: ha.homelab.local
  name: home-assistant
spec:
  ports:
    - port: 443
      targetPort: 8123
  selector:
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      nodeSelector:
        node-role.kubernetes.io/invertor: "true"
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2025.4.2
          resources:
            requests:
              cpu: 400m
              memory: 768Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 2000m
              memory: 3Gi
              ephemeral-storage: 1Gi
          ports:
            - containerPort: 8123
          securityContext:
            privileged: true
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config
            - mountPath: /dev/ttyUSB0
              name: must-invertor-usb
            - mountPath: /cert
              name: tls-cert
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: pg-homeassistant-app
                  key: uri
      volumes:
        - name: home-assistant-config
          nfs:
            server: <NFS_STOR_0_SERVER>
            path: <NFS_N0_PATH>/system/homeassistant
        - name: must-invertor-usb
          hostPath:
            path: /dev/ttyUSB0
        - name: tls-cert
          secret:
            secretName: ha.<homelab-domain>-cert
