###################################################################################################
#
# Postgresql Database cluster, using CNPG
#
###################################################################################################

#
# Cluster definition
#
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-openproject
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-bookworm
  monitoring:
    enablePodMonitor: true

  # Create PVC templates on local storage for each Postgres pod
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: local-path
      volumeMode: Filesystem

  # Import existing database
  bootstrap:
    initdb: null
    recovery:
      source: pg-openproject

  # Backup strategy
  backup:
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 16
      destinationPath: "s3://cnpg"
      endpointURL: "http://minio.backend:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"

  # WAL backup clusters
  externalClusters:
    - name: pg-openproject
      barmanObjectStore:
        data:
          compression: bzip2
        wal:
          compression: bzip2
        destinationPath: "s3://cnpg"
        endpointURL: "http://minio.backend:9000"
        s3Credentials:
          accessKeyId:
            name: cnpg-minio-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: cnpg-minio-creds
            key: ACCESS_SECRET_KEY

  # Force Postgres to be running on NAS node
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/nas: "nas"
#
# Backup schedules
#
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-openproject-local-schedule
spec:
  schedule: "0 5 */12 * * *" # For local store - backup every hour
  backupOwnerReference: self
  cluster:
    name: pg-openproject
