apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-retention-policy-agent
  namespace: tekton-pipelines
spec:
  template:
    spec:
      containers:
        - name: retention-policy-agent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-tekton-results-app
                  key: host
            - name: DB_NAME
              value: app
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-tekton-results-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-tekton-results-app
                  key: password
