apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  jdbc-password: <sonarqube-db-pass>
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  passcode: <sonarqube-monitoring-passcode>
