controller:
  name: nginx-ext
  hostNetwork: false

  ingressClass: nginx
  ingressClassByName: true
  ingressClassResource:
    name: nginx
    enabled: true

  tolerations:
    - key: "nas"
      operator: "Equal"
      value: "true"
      effect: NoSchedule

  ## Enable cert manager for Virtual Server resources. Requires controller.enableCustomResources.
  enableCertManager: false

  service:
    ## The list of external IPs for the Ingress Controller service.
    type: LoadBalancer
    externalTrafficPolicy: Local
    # -- Annotations to be added to the external controller service. See `controller.service.internal.annotations` for annotations to be added to the internal controller service.
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.30.240
    ipFamilies:
      - IPv4

  kind: DaemonSet
  resources:
    requests:
      cpu: 100m
      memory: 150m

prometheus:
  create: false
