apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-main
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.9-bookworm
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.5-bookworm
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-vectorchord
spec:
  images:
    - major: 16
      image: tensorchord/cloudnative-vectorchord:16.9-0.4.2
    - major: 17
      image: tensorchord/cloudnative-vectorchord:17.5-0.4.2
