apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: homebox
  name: homebox
spec:
  ports:
    - port: 80
      targetPort: web
  selector:
    app.kubernetes.io/name: homebox
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  labels:
    app.kubernetes.io/name: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homebox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homebox
    spec:
      automountServiceAccountToken: false
      containers:
        - name: homebox
          image: sysadminsmedia/homebox:0.19.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Kyiv
            - name: HBOX_OPTIONS_ALLOW_REGISTRATION
              value: "false"
            - name: HBOX_OPTIONS_ALLOW_ANALYTICS
              value: "false"
            - name: HBOX_DATABASE_DRIVER
              value: postgres
            - name: HBOX_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-homebox-app
                  key: host
            - name: HBOX_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-homebox-app
                  key: port
            - name: HBOX_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-homebox-app
                  key: user
            - name: HBOX_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-homebox-app
                  key: password
            - name: HBOX_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-homebox-app
                  key: dbname
          ports:
            - containerPort: 7745
              name: web
          volumeMounts:
            - mountPath: /data
              name: homebox
      volumes:
        - name: homebox
          persistentVolumeClaim:
            claimName: homebox
