apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
      path: "operators/cnpg"
      directory:
        recurse: true
        include: "*.yaml"
        exclude: 'values.yaml'
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.2
      chart: cloudnative-pg
      helm:
        valueFiles:
          - $homelab/operators/cnpg/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: operators

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
