apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
      path: 'operators/prometheus'
      directory:
        recurse: true
        include: '*.yaml'
        exclude: 'values.yaml'
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 71.1.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $homelab/operators/prometheus/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: operators

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
