apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pushgateway
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 3.0.0
      chart: prometheus-pushgateway
      helm:
        valueFiles:
          - $homelab/operators/prometheus-pushgateway/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: operators

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
