apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
      path: "operators/rook"
      directory:
        recurse: true
        include: "*.yaml"
        exclude: 'values.yaml'
    - repoURL: https://charts.rook.io/release
      targetRevision: v1.17.1
      chart: rook-ceph
      helm:
        valueFiles:
          - $homelab/operators/rook/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
