apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.45.12
      chart: argo-workflows
      helm:
        valueFiles:
          - $homelab/dev-env/argo-workflows/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
