apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://helm.goharbor.io
      targetRevision: 1.16.2
      chart: harbor
      helm:
        valueFiles:
          - $homelab/dev-env/harbor/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - kind: Secret
      name: "harbor-jobservice"
      jsonPointers:
        - /data/JOBSERVICE_SECRET
    - kind: Secret
      name: "harbor-registry"
      jsonPointers:
        - /data/REGISTRY_HTTP_SECRET
    - kind: Secret
      name: "harbor-registry-htpasswd"
      jsonPointers:
        - /data/REGISTRY_HTPASSWD
    - kind: Secret
      name: "harbor-core-internal-tls"
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - kind: Secret
      name: "harbor-jobservice-internal-tls"
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - kind: Secret
      name: "harbor-portal-internal-tls"
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - kind: Secret
      name: "harbor-registry-internal-tls"
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - kind: Secret
      name: "harbor-trivy-internal-tls"
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
