apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://helm.goharbor.io
      targetRevision: 1.17.1
      chart: harbor
      helm:
        valueFiles:
          - $homelab/dev-env/harbor/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# Required due to used Helm chart
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
        - /data/REGISTRY_HTPASSWD
        - /data/JOBSERVICE_SECRET
        - /data/REGISTRY_HTTP_SECRET
        - /data/CSRF_KEY
        - /data/secret
    - kind: Deployment
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1tls
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1secret-core
        - /spec/template/metadata/annotations/checksum~1secret-jobservice
    - kind: StatefulSet
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1tls
