apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
spec:
  project: homelab

  source:
    repoURL: https://github.com/MornieOhtar/homelab.git
    targetRevision: HEAD
    path: dev-env/it-tools

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
