apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
spec:
  project: homelab

  sources:
    - repoURL: https://github.com/MornieOhtar/homelab.git
      targetRevision: HEAD
      ref: homelab
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      targetRevision: 2025.2.0
      chart: sonarqube
      helm:
        valueFiles:
          - $homelab/dev-env/sonarqube/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - kind: StatefulSet
      group: apps
      jsonPointers:
        - /spec/replicas
