apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ceph-local
spec:
  configuration:
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 16
    destinationPath: "s3://cnpg"
    endpointURL: "http://rook-ceph-rgw-backup-ssd.rook-ceph.svc:80"
    s3Credentials:
      accessKeyId:
        name: cnpg-local-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-local-s3
        key: ACCESS_SECRET_KEY
  retentionPolicy: "30d"
