apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-creds
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_S3_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_S3_SECRET | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-creds
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
data:
  ACCESS_KEY_ID: <CNPG_MINIO_KEY_ID | base64encode>
  ACCESS_SECRET_KEY: <CNPG_MINIO_SECRET | base64encode>
