apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp-exporter
  labels:
    app.kubernetes.io/instance: mktxp-exporter
spec:
  selector:
    matchLabels:
      app: mktxp-exporter
  template:
    metadata:
      labels:
        app: mktxp-exporter
    spec:
      containers:
        - name: mktxp-exporter
          image: ghcr.io/akpw/mktxp:1.2.10
          args:
            - --cfg-dir
            - /mktxp_config
            - export
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: mktxp-credentials
              mountPath: /mktxp_config
          ports:
            - containerPort: 49090
      volumes:
        - name: mktxp-credentials
          secret:
            secretName: mktxp-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: mktxp-exporter
  labels:
    app.kubernetes.io/instance: mktxp-exporter
spec:
  selector:
    app: mktxp-exporter
  ports:
    - port: 49090
      targetPort: 49090
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mikrotik-exporter
  namespace: operators
  labels:
    release: prometheus-operator
    jobLabel: mikrotik-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mktxp-exporter
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - path: /metrics
      port: metrics
