apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: k8up-schedule-backend-local
spec:
  podSecurityContext:
    runAsGroup: 0
    runAsUser: 0
  backend:
    s3:
      endpoint: http://minio.backend:9000
      bucket: k8up
      accessKeyIDSecretRef:
        name: k8up-local-minio
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-local-minio
        key: ACCESS_SECRET_KEY
    repoPasswordSecretRef:
      name: k8up-local-restic
      key: restic-password
  backup:
    schedule: '30 */1 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    promURL: http://prometheus-pushgateway.operators:9091
  check:
    schedule: '@daily-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    promURL: http://prometheus-pushgateway.operators:9091
  prune:
    schedule: '@daily-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    retention:
      keepLast: 12
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 12
      keepYearly: 100
